version: 0.2

phases:
  build:
    commands:
       - echo "starting build..."
       - ds=$(date +"%y%m%d.%S")
       # Build a fat jar of our code using SBT
       #- sbt assembly
       - echo "hello joker" > joke${ds}.txt
       - aws s3 cp joke${ds}.txt s3://plume-development-test-scala-build
       # Since we want our pipeline to automatically deploy our changes, we also assume our Github repo also has a Cloud Formation template
       # that contains any resources we need to create for say a Lambda Function, e.x. maybe we need to create a new DynamoDB table
 artifacts:
  files:
    # These are our "artifacts", e.g. the output of our build system we'd like Code Build to do something with
    - joke${ds}.txt
